print('Произведем несколько операций с двумя числами:')
x = int(input('Введите первое число - '))
y = int(input('Введите второе число - '))
# x = int(x)
# y = int(y)
# print(type(x), type(y))
print("x + y = ", x+y)
print("x - y = ", x-y)
print("x * y = ", x*y)
print("x / y = ", x/y)
print("x ^ y = ", x**y)
print("x / y = ", x//y,"- Целочисленное деление")
print("x % y = ", x%y, "- Остаток от деления")
